
targets:
  clab-gribi-srl1:
    username: admin
    password: admin
    skip-verify: true
  clab-gribi-srl2:
    username: admin
    password: admin
    skip-verify: true

gnmi-server:
  address: :57400
